export interface apiDriverModel {
  id: number;
  name: string;
  gender: string;
  dob: string;
  age: number;
  nic: string;
  nicexpiry: Date;
  licensenumber: string;
  licensetypeid: number;
  licenseexpiry: Date;
  licenseverified: number;
  designation: string;
  department: string;
  permitnumber: string;
  permitissue: Date;
  permitexpiry: Date;
  medicalexpiry: Date;
  bloodgroupid: number;
  contractorid: number;
  visualid: number;
  ddccount: number;
  experience: number;
  code: string;
  comment: string;
  createdby: string;
  isEdit: boolean;
  message: string;
}
