export const Menu = {
  menu: [
    {
      path: '/dashboard',
      name: 'Dashboard',
      roles: ['admin', 'director', 'biller', 'manager', 'staff', 'member'],
      icon: 'fa-solid fa-house fa-flip me-1',
    },
  ],
  dropdownMenus: [
    {
      name: 'Drivers',
      icon: 'fa-solid fa-truck-moving fa-bounce me-1',
      id: 'driver',
      testid: 'drivers',
      roles: ['admin', 'director', 'manager', 'staff', 'member'],
      items: [
        {
          name: 'All Drivers',
          path: '/alldrivers',
          testid: 'alldrivers',
          roles: ['admin', 'director', 'manager', 'staff', 'member'],
          icon: 'fa-solid fa-truck-moving me-1',
        },
        {
          name: 'Add Driver',
          path: '/adddriver',
          testid: 'adddriver',
          roles: ['admin', 'director', 'manager', 'staff', 'member'],
          icon: 'fa-solid fa-plus me-1',
        },
        {
          name: 'Drivers Report',
          path: '/driversreport',
          testid: 'driverreport',
          roles: ['admin', 'director', 'manager', 'staff'],
          icon: 'fa-solid fa-database me-1',
        },
      ],
    },
    {
      name: 'Assessments',
      icon: 'fa-solid fa-table-cells fa-beat me-1',
      id: 'assessments',
      testid: 'assessments',
      roles: ['admin', 'director', 'manager', 'staff', 'member'],
      items: [
        {
          name: 'All Assessments',
          path: '/allassessments',
          testid: 'allassessments',
          roles: ['admin', 'director', 'manager', 'staff', 'member'],
          icon: 'fa-solid fa-table-cells me-1',
        },
        {
          name: 'Add Assessment',
          path: '/addassessment',
          testid: 'addassessment',
          roles: ['admin', 'director', 'manager', 'staff', 'member'],
          icon: 'fa-solid fa-table me-1',
        },
        {
          name: 'Assessments Report',
          path: '/assessmentsreport',
          testid: 'assessmentreport',
          roles: ['admin', 'director', 'manager', 'staff'],
          icon: 'fa-solid fa-database me-1',
        },
        {
          name: 'Assessments Configure',
          path: '/assessmentsconfigure',
          testid: 'assessmentconfigure',
          roles: ['admin', 'director', 'manager'],
          icon: 'fa-solid fa-wrench me-1',
        },
      ],
    },
    {
      name: 'Training',
      icon: 'fa-solid fa-laptop-code fa-beat-fade me-1',
      id: 'training',
      testid: 'trainings',
      roles: ['admin', 'director', 'biller', 'manager'],
      items: [
        {
          name: 'All Trainings',
          path: '/alltrainings',
          testid: 'alltrainings',
          roles: ['admin', 'director', 'biller', 'manager'],
          icon: 'fa-solid fa-book-open-reader me-1',
        },
        {
          name: 'Add Training',
          path: '/addtraining',
          testid: 'addtraining',
          roles: ['admin', 'director', 'manager'],
          icon: 'fa-solid fa-network-wired me-1',
        },
        {
          name: 'Training Report',
          path: '/trainingsreport',
          testid: 'trainingreport',
          roles: ['admin', 'director', 'biller', 'manager'],
          icon: 'fa-solid fa-laptop-file me-1',
        },
      ],
    },
    {
      name: 'Settings',
      icon: 'fa-solid fa-cog fa-spin me-1',
      id: 'settings',
      testid: 'settings',
      roles: ['admin', 'director', 'manager'],
      items: [
        {
          name: 'Trainers',
          path: '/trainer',
          testid: 'trainers',
          roles: ['admin', 'director', 'manager'],
          icon: 'fa-solid fa-person-chalkboard me-1',
        },
        {
          name: 'BloodGroups',
          path: '/blood',
          testid: 'bgs',
          roles: ['admin', 'director', 'manager'],
          icon: 'fa-solid fa-droplet me-1',
        },
        {
          name: 'Category',
          path: '/category',
          testid: 'categories',
          roles: ['admin', 'director', 'manager'],
          icon: 'fa-solid fa-layer-group me-1',
        },
        {
          name: 'Clients',
          path: '/client',
          testid: 'clients',
          roles: ['admin', 'director', 'manager'],
          icon: 'fa-solid fa-business-time me-1',
        },
        {
          name: 'Contractors',
          path: '/contractor',
          testid: 'contractors',
          roles: ['admin', 'director', 'manager'],
          icon: 'fa-solid fa-building me-1',
        },
        {
          name: 'Course',
          path: '/course',
          testid: 'courses',
          roles: ['admin', 'director', 'manager'],
          icon: 'fa-solid fa-graduation-cap me-1',
        },
        {
          name: 'DL Types',
          path: '/dltype',
          testid: 'dltypes',
          roles: ['admin', 'director', 'manager'],
          icon: 'fa-solid fa-id-badge me-1',
        },
        {
          name: 'Industries',
          path: '/industries',
          testid: 'industries',
          roles: ['admin', 'director', 'manager'],
          icon: 'fa-solid fa-industry me-1',
        },
        {
          name: 'Locations',
          path: '/location',
          testid: 'locations',
          roles: ['admin', 'director', 'manager'],
          icon: 'fa-solid fa-location-dot me-1',
        },
        {
          name: 'Results',
          path: '/result',
          testid: 'results',
          roles: ['admin', 'director', 'manager'],
          icon: 'fa-solid fa-square-poll-vertical me-1',
        },
        {
          name: 'Stages',
          path: '/stage',
          testid: 'stages',
          roles: ['admin', 'director', 'manager'],
          icon: 'fa-solid fa-person-booth me-1',
        },
        {
          name: 'Titles',
          path: '/title',
          testid: 'titles',
          roles: ['admin', 'director', 'manager'],
          icon: 'fa-brands fa-phoenix-framework me-1',
        },
        {
          name: 'Vehicle',
          path: '/vehicle',
          testid: 'vehicles',
          roles: ['admin', 'director', 'manager'],
          icon: 'fa-solid fa-truck me-1',
        },
        {
          name: 'Visual',
          path: '/visual',
          testid: 'visuals',
          roles: ['admin', 'director', 'manager'],
          icon: 'fa-solid fa-eye me-1',
        },
      ],
    },
    // {
    //   name: 'User',
    //   icon: 'fa-solid fa-circle-user me-1',
    //   id: 'user',
    //   roles: ['admin', 'manager', 'staff', 'member'],
    //   items: [
    //     {
    //       name: 'Profile',
    //       path: '/profile',
    //       roles: ['admin', 'manager', 'staff', 'member'],
    //       icon: 'fa-solid fa-user me-1',
    //     },
    //     {
    //       name: 'LogOut',
    //       path: '/login',
    //       roles: ['admin', 'manager', 'staff', 'member'],
    //       icon: 'fa-solid fa-right-from-bracket me-1',
    //     },
    //   ],
    // },
  ],
};
